- name: GitHub metrics as SVG image
  # You may pin to the exact commit or the version.
  # uses: lowlighter/metrics@9b574376230687a8e9cb354fa27ad5f951778d9a
  uses: lowlighter/metrics@v3.3
  with:
    # Metrics base content
    base: # optional, default is header, activity, community, repositories, metadata
    # Number of repositories to use
    repositories: # optional, default is 100
    # Include forks in metrics
    repositories_forks: # optional
    # GitHub Personal Token
    token: 
    # GitHub username
    user: # optional, default is 
    # GitHub Token used to commit metrics
    committer_token: # optional, default is 
    # Branch used to commit rendered metrics
    committer_branch: # optional, default is 
    # Rendered metrics output path
    filename: # optional, default is github-metrics.svg
    # SVG optimization
    optimize: # optional, default is true
    # Additional community templates to setup
    setup_community_templates: # optional, default is 
    # Template to use
    template: # optional, default is classic
    # Additional query parameters
    query: # optional, default is {}
    # Timezone used
    config_timezone: # optional, default is 
    # Configure content order
    config_order: # optional, default is 
    # SVG CSS animations
    config_animations: # optional, default is true
    # Image padding
    config_padding: # optional, default is 6%
    # Output image format
    config_output: # optional, default is svg
    # Die on plugins errors
    plugins_errors_fatal: # optional
    # Debug logs
    debug: # optional
    # Verify SVG
    verify: # optional
    # Debug flags
    debug_flags: # optional, default is 
    # Enable dry-run
    dryrun: # optional
    # Use mocked data instead of live APIs
    use_mocked_data: # optional
    # Use pre-built image from GitHub registry
    use_prebuilt_image: # optional, default is 
    # Display recent activity
    plugin_activity: # optional
    # Maximum number of events to display
    plugin_activity_limit: # optional, default is 5
    # Maximum event age
    plugin_activity_days: # optional, default is 14
    # Events types to keep
    plugin_activity_filter: # optional, default is all
    # Display data from your AniList account
    plugin_anilist: # optional
    # Medias types to display
    plugin_anilist_medias: # optional, default is anime, manga
    # Sections to display
    plugin_anilist_sections: # optional, default is favorites
    # Maximum number of entries to display per section
    plugin_anilist_limit: # optional, default is 2
    # Shuffle AniList data
    plugin_anilist_shuffle: # optional, default is true
    # AniList login
    plugin_anilist_user: # optional, default is .user.login
    # Display follow-up of repositories issues and pull requests
    plugin_followup: # optional
    # Display gists metrics
    plugin_gists: # optional
    # Display coding habits metrics
    plugin_habits: # optional
    # Number of events to use
    plugin_habits_from: # optional, default is 200
    # Maximum event age
    plugin_habits_days: # optional, default is 14
    # Display coding habits collected facts based on recent activity
    plugin_habits_facts: # optional, default is true
    # Display coding habits charts based on recent activity
    plugin_habits_charts: # optional
    # Display an isometric view of your commits calendar
    plugin_isocalendar: # optional
    # Set time window shown by isometric calendar
    plugin_isocalendar_duration: # optional, default is half-year
    # Display most used languages metrics
    plugin_languages: # optional
    # Languages to ignore
    plugin_languages_ignored: # optional, default is 
    # Repositories to skip
    plugin_languages_skipped: # optional, default is 
    # Custom languages colors
    plugin_languages_colors: # optional, default is github
    # Additional details
    plugin_languages_details: # optional, default is 
    # Display lines of code metrics
    plugin_lines: # optional
    # Display your music tracks
    plugin_music: # optional
    # Music provider
    plugin_music_provider: # optional, default is 
    # Music provider personal token
    plugin_music_token: # optional, default is 
    # Plugin mode
    plugin_music_mode: # optional, default is 
    # Embed playlist url
    plugin_music_playlist: # optional, default is 
    # Maximum number of tracks to display
    plugin_music_limit: # optional, default is 4
    # Music provider username
    plugin_music_user: # optional, default is .user.login
    # Display a website Google PageSpeed metrics
    plugin_pagespeed: # optional
    # Audited website
    plugin_pagespeed_url: # optional, default is .user.website
    # Detailed audit result
    plugin_pagespeed_detailed: # optional
    # Display a screenshot of your website
    plugin_pagespeed_screenshot: # optional
    # PageSpeed token
    plugin_pagespeed_token: # optional, default is 
    # Display GitHub users from various affiliations
    plugin_people: # optional
    # Maximum number of user to display
    plugin_people_limit: # optional, default is 28
    # Size of displayed GitHub users' avatars
    plugin_people_size: # optional, default is 28
    # Affiliations to display
    plugin_people_types: # optional, default is followers, following
    # GitHub users to personally thanks
    plugin_people_thanks: # optional, default is 
    # Use identicons instead of avatars
    plugin_people_identicons: # optional
    # Display recent posts
    plugin_posts: # optional
    # Posts external source
    plugin_posts_source: # optional, default is 
    # Maximum number of posts to display
    plugin_posts_limit: # optional, default is 4
    # Posts external source username
    plugin_posts_user: # optional, default is .user.login
    # Display active projects
    plugin_projects: # optional
    # Maximum number of projects to display
    plugin_projects_limit: # optional, default is 4
    # List of repository project identifiers to disaplay
    plugin_projects_repositories: # optional, default is 
    # Display projects descriptions
    plugin_projects_descriptions: # optional
    # Display stargazers metrics
    plugin_stargazers: # optional
    # Display recently starred repositories
    plugin_stars: # optional
    # Maximum number of stars to display
    plugin_stars_limit: # optional, default is 4
    # Display starred topics
    plugin_topics: # optional
    # Plugin mode
    plugin_topics_mode: # optional, default is starred
    # Sorting method of starred topics
    plugin_topics_sort: # optional, default is stars
    # Maximum number of topics to display
    plugin_topics_limit: # optional, default is 15
    # Display repositories traffic metrics
    plugin_traffic: # optional
    # Display recent tweets
    plugin_tweets: # optional
    # Twitter API token
    plugin_tweets_token: # optional, default is 
    # Maximum number of tweets to display
    plugin_tweets_limit: # optional, default is 2
    # Twitter username
    plugin_tweets_user: # optional, default is .user.twitter
